// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuDoLPU3qVCbfMvLe2bh6tgXDxaE9BQJg',
    appId: '1:306103682715:web:de9c6e97a90a136c95a83e',
    messagingSenderId: '306103682715',
    projectId: 'example-abfd2',
    authDomain: 'example-abfd2.firebaseapp.com',
    storageBucket: 'example-abfd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFEB4XtgFDr3qy11RJo-bzLNKSAyDC9nE',
    appId: '1:306103682715:android:14c487d96cf7c34d95a83e',
    messagingSenderId: '306103682715',
    projectId: 'example-abfd2',
    storageBucket: 'example-abfd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX8tt3Fhl53UgkNN4oJVwY5iMbsYBpGpU',
    appId: '1:306103682715:ios:a5616eb26d951c6495a83e',
    messagingSenderId: '306103682715',
    projectId: 'example-abfd2',
    storageBucket: 'example-abfd2.firebasestorage.app',
    iosBundleId: 'com.example.testFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX8tt3Fhl53UgkNN4oJVwY5iMbsYBpGpU',
    appId: '1:306103682715:ios:a5616eb26d951c6495a83e',
    messagingSenderId: '306103682715',
    projectId: 'example-abfd2',
    storageBucket: 'example-abfd2.firebasestorage.app',
    iosBundleId: 'com.example.testFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuDoLPU3qVCbfMvLe2bh6tgXDxaE9BQJg',
    appId: '1:306103682715:web:6c9c761e363dea1e95a83e',
    messagingSenderId: '306103682715',
    projectId: 'example-abfd2',
    authDomain: 'example-abfd2.firebaseapp.com',
    storageBucket: 'example-abfd2.firebasestorage.app',
  );
}
